### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by xan2622** [OkGoDoIt/Office-Ribbon-2010#7]
The URL for the demo is broken.
https://okgodoit.com/ribbon/

It might be interesting to upload the project on another website.

**Comment by xan2622** [comment]
https://okgodoit.com/ribbon/ doesn't work.
http://okgodoit.com/ribbon/ does.

**Comment by OkGoDoIt** [comment]
I've fixed the ssl support. This was a very old project and I did not have ssl on that server.  Working now :-)
